export const PATH = {
  LOGIN: "/login",
  LOGOUT: "/logout",
  CHANGE_PASSWORD: "/changePassword/:id",
  DELETED: "/deleted",
  ID: "/:id",
  EDIT: "/edit/:id",
  DELETE: "/delete/:id",
  RESTORE: "/restore/:id",
  FORCE_DELETE: "/forceDelete/:id",
  EMAIL_OTP: "/emailOTP",
  RESTORE_PASSWORD: "/resetPassword",
  DEFAULT_DESIGN: "/createDefault",
  REMOVE_DEFAULT: "/removeDefault/:id",
  USER_PROFILE: "/view/userProfile",
};
