export const PATH = {
  LOGIN: "/login",
  LOGOUT: "/logout",
  CHANGE_PASSWORD: "/changePassword/:id",
  DELETED: "/deleted",
  ID: "/:id",
  EDIT: "/edit/:id",
  DELETE: "/delete/:id",
  RESTORE: "/restore/:id",
  FORCE_DELETE: "/forceDelete/:id",
  EMAIL_OTP: "/emailOTP",
  RESTORE_PASSWORD: "/resetEmailPassword",
  DEFAULT_DESIGN: "/createDefault",
  FIND_DEFAULT: "/findDefault/:id",
  REMOVE_DEFAULT: "/removeDefault/:id",
};
