export const RESOURCE = {
  AUTH: "Auth",
  DEV: "dev",
  PRODUCTION: "production",
  DEVELOPMENT: "development",
  API: "/api/",
  V1: "v1/",
  V2: "v2/",
  VALIDATION_ERROR: "ValidationError",
  NOT_FOUND: "Not Found",
  IMAGE: "projectImages",
  IMAGES: "images",
  FINISH: "finish",
  ID: "_id",
  ROLE: "role",
  PASSWORD: "+password",
  USERS: "users",
  CONTENTS: "contents",
};
