export const RESOURCE = {
  AUTH: "Auth",
  DEV: "dev",
  PRODUCTION: "production",
  DEVELOPMENT: "development",
  API: "/api/",
  V1: "v1/",
  V2: "v2/",
  VALIDATION_ERROR: "ValidationError",
  NOT_FOUND: "Not Found",
  IMAGE: "projectImages",
  IMAGES: "images",
  SUBMISSIONS: "submissions",
  FINISH: "finish",
  ID: "_id",
  ROLE: "role",
  PASSWORD: "+password",
  USERS: "users",
  USER: "user",
  CONTENTS: "contents",
  CONTENT: "content",
  INPUT_TYPES: "inputTypes",
  INPUT_TYPE: "inputType",
  DESIGNS: "designs",
  DESIGN: "design",
  SETTINGS: "settings",
  SETTING: "setting",
  PUBLISHES: "publishes",
  PUBLISH: "publish",
  FORMS: "forms",
  FORM: "form",
  SUBMISSIONS: "submissions",
  SUBMISSION: "submission",
  GMAIL: "gmail",	
  LINKS: "links",
};
